### PR TITLE
Database URLs

### PR DESCRIPTION
**Pull request by TobiasDeBruijn**
While trying to deploy Chroma to staging, I realized that Sticky's server uses database urls rather than separate parameters.
This PR adds support for this.

## Changes
- Add support for database URLs
- Switched out `refinery` for `sqlx::migrate` for migrations

@HugoPeters1024 Would you mind trying to deploy with this version? I've attached a compiled binary. (Had to zip it so GitHub would accept it)
[server-x86_64-unknown-linux-musl.zip](https://github.com/svsticky/chroma/files/12651814/server-x86_64-unknown-linux-musl.zip)

### CODE REVIEW

**Comment by HugoPeters1024** [comment]
> @HugoPeters1024 Would you mind trying to deploy with this version? I've attached a compiled binary. (Had to zip it so GitHub would accept it)

I'll give it a go right now

**Comment by HugoPeters1024** [comment]
@TobiasDeBruijn The database connection now seems to work. (That is, it does not crash on startup). However, the frontend (you can visit https://chroma.dev.svsticky.nl) does not work yet because it is making requests to `localhost:8000`. Perhaps you gave me a development build instead of a release one?

**Comment by TobiasDeBruijn** [comment]
Sweet. That's that solved.

I've attached an updated frontend. It should be extracted into `/var/www/chroma/frontend`, make sure you match the existing file structure! iirc the contents have to be moved out of the `dist/` folder, or use `--strip-components=1` as an argument to `tar` when extracting.

By the way: the cert for `https://chroma.dev.svsticky.nl/` isn't valid, and the site has HSTS enabled, so it cannot be visited.

[frontend.tar.gz](https://github.com/svsticky/chroma/files/12652132/frontend.tar.gz)

**Comment by HugoPeters1024** [comment]
> I've attached an updated frontend. It should be extracted into /var/www/chroma/frontend, make sure you match the existing file structure! iirc the contents have to be moved out of the dist/ folder, or use --strip-components=1 as an argument to tar when extracting.

Nice, it now seems to work!

> By the way: the cert for https://chroma.dev.svsticky.nl/ isn't valid, and the site has HSTS enabled, so it cannot be visited.

This is known issue, if you visit the page in incognito mode you are able to proceed anyway.

**Comment by TobiasDeBruijn** [comment]
Sweet that it works.

In Chrome one can type `thisisunsafe` on the error page. Though in Firefox, my primary browser, it's not possible to view the page. Irregardless of private mode or normal mode.

Is there an open issue anywhere to fix the cert issue, or disable HSTS for dev.svsticky.nl?

**Comment by TobiasDeBruijn** [comment]
@HugoPeters1024 Could we push to production as well? After I cut a new release of course

**Pull request merged**
